#!/bin/sh
# Git hook that checkes if the unit tests and the tsc are ok.
# To use it, cp pre-commit .git/hooks/pre-commit
# Author: skaldo on the 14.05.2016

set -e

cd CitizenApplication

gulp pre-commit
result=$?

if [ $result -ne 0 ]; then
    echo "Please fix the errors before commiting."
    exit 1
fi
